AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'lib/aircana/human_logger.rb'
    - 'lib/aircana/system_checker.rb'
    - 'lib/aircana/cli/commands/add_directory.rb'
    - 'lib/aircana/cli/commands/hooks.rb'
    - 'lib/aircana/cli/commands/install.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/aircana/cli/commands/add_directory.rb'
    - 'lib/aircana/cli/commands/hooks.rb'
    - 'lib/aircana/cli/commands/install.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/aircana/cli/commands/hooks.rb'
    - 'lib/aircana/cli/commands/install.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/aircana/cli/commands/hooks.rb'
    - 'lib/aircana/cli/commands/install.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/aircana/cli/commands/hooks.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/aircana/cli/commands/hooks.rb'
