services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  bundle_cache: