#!/usr/bin/env ruby

# frozen_string_literal: true

require "aircana"

Aircana.configure do |config|
  config.confluence_base_url = ENV.fetch("CONFLUENCE_BASE_URL", nil)
  config.confluence_username = ENV.fetch("CONFLUENCE_USERNAME", nil)
  config.confluence_api_token = ENV.fetch("CONFLUENCE_API_TOKEN", nil)
  config.llm_provider = ENV.fetch("AIRCANA_LLM_PROVIDER", nil)
  config.bedrock_region = ENV.fetch("AIRCANA_BEDROCK_REGION", nil)
  config.bedrock_model = ENV.fetch("AIRCANA_BEDROCK_MODEL", nil)
end

Aircana::CLI::App.start(ARGV)
